name = "apimo-proxy"
type = "javascript"
account_id = "geraldineggg"
workers_dev = true
compatibility_date = "2023-01-01"

[vars]
API_URL = "https://api.apimo.pro/agencies/23385/properties"
API_TOKEN = "afaa418252a1dfece10ffa74d2a1fcd0fda914f6"
PROVIDER_ID =  "3993"

[build]
command = "npm install && npm run build"

